name: football_club_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  uni_links: ^0.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  image_picker: ^1.1.2
  intl: 0.19.0
  logger: ^2.3.0
  maps_launcher: ^2.0.2+1
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  rxdart: 0.27.7
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.6.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
