// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZAUfdtlegp84dovR4bXrAAxd8W8blKaI',
    appId: '1:928258584201:web:29fe18bba5af27d41ae058',
    messagingSenderId: '928258584201',
    projectId: 'football-club-app-9d04d',
    authDomain: 'football-club-app-9d04d.firebaseapp.com',
    storageBucket: 'football-club-app-9d04d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5UBSCPVK0RwF4UMchdyEi-jjji1IMxkc',
    appId: '1:928258584201:android:5cd0809829c396c91ae058',
    messagingSenderId: '928258584201',
    projectId: 'football-club-app-9d04d',
    storageBucket: 'football-club-app-9d04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwfYNUcV5Yc8Qwe4GSbstkeb1sOpR0z4',
    appId: '1:928258584201:ios:5912c3906d0af6491ae058',
    messagingSenderId: '928258584201',
    projectId: 'football-club-app-9d04d',
    storageBucket: 'football-club-app-9d04d.appspot.com',
    iosBundleId: 'com.example.footballClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPwfYNUcV5Yc8Qwe4GSbstkeb1sOpR0z4',
    appId: '1:928258584201:ios:5912c3906d0af6491ae058',
    messagingSenderId: '928258584201',
    projectId: 'football-club-app-9d04d',
    storageBucket: 'football-club-app-9d04d.appspot.com',
    iosBundleId: 'com.example.footballClubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZAUfdtlegp84dovR4bXrAAxd8W8blKaI',
    appId: '1:928258584201:web:c5f79dc0b49279751ae058',
    messagingSenderId: '928258584201',
    projectId: 'football-club-app-9d04d',
    authDomain: 'football-club-app-9d04d.firebaseapp.com',
    storageBucket: 'football-club-app-9d04d.appspot.com',
  );
}
